version: '3.9'
services:
  sample-api:
    container_name: sample-api
    build: .
    volumes:
      - type: bind
        source: ./db
        target: /api/db
    ports:
      - 8081:8081
    tty: true
    stdin_open: true
