@startuml
' 変数定義
Participant curl as FE
Participant Echo as BE
Participant Gorm as OR
Participant SQLite as DB

' シーケンス
FE -> BE : Request
activate BE
    BE -> OR : 構造体
    note left
    Josnフォーマット
    end note
    activate OR
        OR -> DB : ORM
        activate DB
        DB --> OR : ORM
        deactivate DB
    OR --> BE : 構造体
    deactivate OR
BE --> FE : Response
deactivate BE

@enduml
