@startuml
' 変数定義
Participant frontend as FE
Participant Echo as BE
Participant Gorm as OR
Participant SQLite as DB

' シーケンス
FE -> BE : Request
activate BE
    BE -> OR : 構造体
    note left
    Request:
    \tパスパラメータ
    \tクエリパラメータ
    Request:
    \tJosnフォーマット
    end note
    activate OR
        OR -> DB : O/Rマッパー
        activate DB
        DB --> OR : O/Rマッパー
        deactivate DB
    OR --> BE : 構造体
    deactivate OR
BE --> FE : Response
deactivate BE

@enduml
